name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2  # Añade el paso de checkout para clonar tu repositorio
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: 'yes'
          # Configura los plugins que deseas utilizar
          plugin_languages: 'yes'
          plugin_starlists: 'yes'
          plugin_starlists_languages: 'yes'
          
          # Asegúrate de configurar otros plugins y opciones según sea necesario
